### ISSUE TITLE
Pre-Season 1 Cards Used for Baelor & Victarion

### ISSUE THREAD

**Issue by nrWillbanks** [brianchuchua/asoiaf-tmg-discord-bot#14]
The card used for Baelor Blacktyde is his old version with old "To The Last." Current Season 1 card face should be this:
![Bealor](https://user-images.githubusercontent.com/72263329/195622987-727d2a7c-a697-4377-a0e2-80aad8e50b2a.png)

Same with Victarion attachment (Season 1 updated "Relentless"):
![Vic](https://user-images.githubusercontent.com/72263329/195623668-3b5c87b5-21e9-435f-a884-db5c0039ada8.png)

**Comment by brianchuchua** [comment]
This has been fixed -- thank you @nrWillbanks
