### ISSUE TITLE
Mag the Mighty (C)

### ISSUE THREAD

**Issue by nrWillbanks** [brianchuchua/asoiaf-tmg-discord-bot#15]
Mag the Mighty should be tagged as a commander (Relevant only for -all requests, since his Combat Unit is identical to his Commander Combat unit).

Request will return 11 cards since he replaces the whole deck, so that's something to consider.

**Comment by brianchuchua** [comment]
Fixed, thanks @nrWillbanks 

My solution is to spit out just a single group image of tactics cards for Commanders like these.

Mag's image: https://asoiaf-tmg-discord-bot.s3.amazonaws.com/images/ff-mag-the-mighty-tactics.png

The infrastructure is built now so future Commanders that replace all tactics cards will receive a similar treatment.
