### ISSUE TITLE
Renly Lord Paramount issue

### ISSUE THREAD

**Issue by nrWillbanks** [brianchuchua/asoiaf-tmg-discord-bot#23]
Requesting "-all" for "Renly Lord Paramount" calls up the correct commander attachment, but also all 9 Renly Tactics Cards for all 3 versions of Renly Commanders. (Tested the other 2 Renly Commanders & they call the correct set of cards with "-all".)

**Comment by brianchuchua** [comment]
Confirming receipt of the request -- I've just been busy maintaining some other projects. I'll circle around to this soonish.

**Comment by brianchuchua** [comment]
Closing this issue since I'm no longer an active contributor.
