### ISSUE TITLE
Planning and insight card missing

### ISSUE THREAD

**Issue by CallMeSophie** [brianchuchua/asoiaf-tmg-discord-bot#24]
"Planning and insight" card from neutrals deck is missing, at least I cannot find it
![40401](https://github.com/brianchuchua/asoiaf-tmg-discord-bot/assets/67827054/9246e72f-6634-48d9-a058-586c29e7f190)

**Comment by CallMeSophie** [comment]
Okay, I looked into code - it seems card is here, it's just called "Tactical approach" in code, which I assume isn't intended

**Comment by brianchuchua** [comment]
Thanks for the report, @CeasarArezzo!

The card was previously called "Tactical Approach" -- that's probably why it's that way.

![image](https://github.com/brianchuchua/asoiaf-tmg-discord-bot/assets/1777011/02a258b1-6361-44ae-963e-89bf2d902226)

I'll look into this history soon and revise.

**Comment by brianchuchua** [comment]
Looks like this was added by our volunteer too.
