### ISSUE TITLE
Missing things after S03 update

### ISSUE THREAD

**Issue by CallMeSophie** [brianchuchua/asoiaf-tmg-discord-bot#25]
Bot is missing recently released boxes:
 - Martell Heroes 2
 - Bolton Starter Set (Dreadfort Archers, new NCUs, new Tactic deck and commander cards, new attachment cards, and new cards for old bolton units)
 - Bolton Heroes 1
 - Dreadfort Spearmen
 - Targaryen Brazen Beasts
 - Lannister Golden Cloaks

Multiple things have been also changed in recent update, [this](https://asoif.s3.amazonaws.com/pdf/pdf/pdf/250/S03_Changelog.pdf) is whole changelog of things that got changed, with new tactics card available [here](https://asoiaf.cmon.com/docs) in respective factions pdf, and rest of cards available [here](https://asoif.s3.amazonaws.com/pdf/pdf/pdf/250/S03_Changelog.pdf), or all of them available on [asoiaf-stats](https://asoiaf-stats.com/builder). There are many errors between files on their website and War Council, so it's likely that some of those cards will be changed in nearest time (or at least we can hope)

**Comment by brianchuchua** [comment]
Oh boy, a little nervous about the differences between the website and War Council.

@CeasarArezzo , do you happen to know which would be correct in the case of a conflict? :)

**Comment by CallMeSophie** [comment]
@brianchuchua as of now, War Council and files on website have been updated - most of them should be correct, so there shouldn't be a difference which one you will use

**Comment by CallMeSophie** [comment]
Also, card Raiders of the Iron Island is probably worth adding. Can be found in War Council - when you create Greyjoy list, just look into their tactics deck and it should be here

**Comment by CallMeSophie** [comment]
Varamyr Commander cards are in really bad quality - they could also use updating

**Comment by brianchuchua** [comment]
Hey @CeasarArezzo -- most of these should have been added by a volunteer. I'm no longer playing ASOIAF TMG but the community is still welcome to push updates to this code and send me new images to use.

I don't think the Varamyr Commander card qualities were updated explicitly. I'm going to close this issue since new cards were added, but feel free to open a new one for that request specifically.
