### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by Pf2eTools** [brianchuchua/asoiaf-tmg-discord-bot#5]
I found a few typos:
- "High Sparrow - His High Holiness", should be "The High Sparrow - His High Holiness"
- "Shyra Errol - La~n~dy of Haystack Hall", has an extra "n"
- "Olenna Tyrell - Olenna Tyrell" should be "Olenna Tyrell - Queen of Thorns"
- "Alister Thorne - Vindictive Overseer" should be "Alliser Thorne - Vindictive Overseer"
- "Ranger Vanguard**s**" is missing the "s"
- "Jorah Mormont - Pentient Betrayer" should be "Jorah Mormont - Penitent Betrayer"
- "Jorah Mormont - Westeros**i** Tactician" missing the "i"

**Comment by brianchuchua** [comment]
Thanks for the report! These were bound to happen since I autogenerated many of the names via a script that also pulled their images.

I'll have this fixed shortly.

**Comment by brianchuchua** [comment]
@Pf2eTools These are fixed and the changes are now live in the bot. :)

**Comment by Pf2eTools** [comment]
You are very quick!
