### ISSUE TITLE
Add more info cards to the bot

### ISSUE THREAD

**Issue by brianchuchua** [brianchuchua/asoiaf-tmg-discord-bot#7]
![image](https://user-images.githubusercontent.com/1777011/189732445-fa79b431-e94d-4487-9115-b61ea8aa52a1.png)

**Comment by brianchuchua** [comment]
Other cards to consider: Objectives, secret missions, player reference cards, terrain, etc.

**Comment by nrWillbanks** [comment]
Drop me a line if you want a hand pulling together image references for many of these various cards (Willybunks on Discord). Most can be grabbed from TTS.

**Comment by brianchuchua** [comment]
@nrWillbanks -- Interesting. By grabbed from TTS, so you mean via screenshots -- or do you happen to know a good source/directory for image files? For objectives and the like I have CMON's official .PDFs but I have to do a lot of manual processing of those into their own images.

**Comment by nrWillbanks** [comment]
I'm on the TTS mod github, so I can grab the files from there.  Let me know the best way to get them to you.
I've got:
- Castle Wall Unit Card
- Siege Decks
- Mission Cards
- Objective Cards
- (Can do reference cards & terrain too, but I'm less certain on the best way to do so & I'm not sure if that will be as useful)

**Comment by brianchuchua** [comment]
@nrWillbanks Oh hey, can you get me added to that GitHub (assuming it's private)? Happy to grab the files directly/contribute to that project too. :)

**Comment by brianchuchua** [comment]
I've added Missions and Objectives.

No one's been asking for the others yet so I'll sit on them.
