### ISSUE TITLE
Baratheon Banners

### ISSUE THREAD

**Issue by nrWillbanks** [brianchuchua/asoiaf-tmg-discord-bot#8]
Can you add Joffrey's "Baratheon Banners" as a searchable card? (Used by his Kingsguard unit)
![Screenshot_20220916-210744-238](https://user-images.githubusercontent.com/72263329/190853982-55b9e7a9-bebc-4140-afc6-efb8bf0acbe6.png)

**Comment by brianchuchua** [comment]
@nrWillbanks -- Done! I added some transparency around the image as well.

`!a baratheon banners` will do the trick. Thanks!
